---
title: "INFORME DE RESULTADOS CARRERA DE LA LUZ 2022"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme:  cerulean
   
---

```{r setup, include=FALSE}
library(flexdashboard)
library(paqueteMET)
library(readr)
library(ggplot2)
library(flexdashboard)
library(dplyr)
library(flextable)
library(psych)


```

Column {data-width=600 .tabset}
----------------------------------------------------------------

### Tiempos de Carrera

**La mayor participación en la carrera se presentó en la categoría abierta, seguida de veteranos A. La de menor participación fue la juvenil**

```{r}

data("CarreraLuz22")
data=CarreraLuz22
ggplot(CarreraLuz22, aes(x = categoria, y = timerun/60 )) +
  geom_jitter(aes(fill = categoria)) 

```


### Estadisticos Generales
**Participaron 1922 personas, la edad media fue de 37.45, la persona con mayor edad tenia 76 años, mientras la menor tenia 15**

```{r}
summary(data$edad)
psych::describe(data$edad)
summarytools::descr(data$edad)

```

### Est.- # Por Categoria
**El 61% de los participantes pertenecían a la categoría abierta, de la cual 677 eran hombres y 502 mujeres**

```{r}

table(data$categoria, data$sex)
table(data$categoria, data$sex) %>% 
  prop.table()

```

### Est.-Frec. Absoluta
**1179 participantes estaban en la categoría abierta**

```{r}
ft1=table(data$categoria)%>% 
  as.data.frame()
colnames(ft1)=c("Categoría", "Frecuencia absoluta")
ft1=flextable(ft1)

set_flextable_defaults(
  font.size = 12, font.family = "Helvetica",
  font.color = "#333333",
  table.layout = "fixed",
  border.color = "red",
  padding.top = 3, padding.bottom = 3,
  padding.left = 4, padding.right = 4)

ft1 <- ft1 %>%
  width(j = 1,  width = 2) %>%
  width(j = 2, width = 1)
ft1
```

### Est.-Frec. Por Intervalos
**El rango de edad se concentró entre las edades de 18 y 40 años, equivalente al 64% de los participantes. El siguente rango de edad donde tuvo mayor afluencia fue entre 41-50 años con 397 participantes**

```{r}
breaks=c(10,18,40,50,60,80)    
Edad.corredores=cut(data$edad, breaks)
summarytools::freq(Edad.corredores)
```

### Grafico por Categorias

```{r}
library(highcharter)
highchart() %>%
  hc_chart(type = 'column',
           options3d = list(
             enabled = TRUE,
             beta = 40,
             alpha = 20
           )) %>%
  
  hc_xAxis(categories = c("1. Juvenil", "2. Abierta", "3. Veteranos A", "4. Veteranos B", "5. Veteranos C")) %>%
  hc_add_series(data$categoria, name = 'Categoria', dataLabels = list(enabled = TRUE)) %>%
  hc_credits(enabled = TRUE,
             text = 'Carrera de la Luz 2022',
             href = 'Carrera 2022') %>%
  hc_exporting(enabled = TRUE) %>%
  hc_plotOptions(line = list(color = "RED",
marker = list(
fillColor = "white",
lineWidth = 2,
lineColor = NULL)))
```


Column {data-width=400}
----------------------------------------------------------------

### Tiempo Mujeres Categoria Abierta

```{r}
data("CarreraLuz22")
data=CarreraLuz22
CarreraLuz22M = subset(CarreraLuz22, CarreraLuz22$sex=="Mujer")
ggplot(CarreraLuz22M, aes(x = categoria, y = timerun/60 )) +
  geom_boxplot(aes(fill = categoria)) 

  
```

### Tiempo Hombres Categoria 

```{r}

data("CarreraLuz22")
data=CarreraLuz22
CarreraLuz22H = subset(CarreraLuz22, CarreraLuz22$sex=="hOMBRE")
ggplot(CarreraLuz22M, aes(x = categoria, y = timerun/60 )) +
  geom_boxplot(aes(fill = categoria))

```

Column { data-width=50 }
----------------------------------------------------------------

### Indicadores

```{r}

valueBox(value = round(mean(data$edad),2),caption = "Edad Promedio Participantes",icon = "fa-users", color = "red")

```


### Velocidad

```{r}


x<-table(CarreraLuz22$timerun/60)

valueBox(value = round(max(CarreraLuz22$timerun/60),3),caption = "Mayor Tiempo",icon = "fas fa-digital-tachograph", color = "blue")
```

### Distancia

```{r}

dis="10.07 KM"
valueBox(value = (dis), caption = "Distancia Recorrida",icon = "fa-road", color = "green")

```

### NUMERO DE ATLETAS

```{r}
valueBox(value = paste(length(CarreraLuz22$timerun),"Atletas"), caption = "Numero de Atletas",icon = "fas fa-user-friends", color = "purple")
```

### MAX VEL

```{r}

valueBox(value = "5.07 M/S ", caption = "Maxima Velocidad",icon = "fas fa-user-friends", color = "gray")
```


### porcentaje mujer

```{r}

valueBox(value = "38.71 % ", caption = "Porcentaje de mujeres",icon = "fas fa-user-friends", color = "pink")
```

